### ISSUE TITLE
0xHelium - some tokens may revert when zero transfer value are made

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#15]
0xHelium

medium

# some tokens may revert when zero transfer value are made
## Summary
some tokens may revert when transferring 0 token value
## Vulnerability Detail
in the rescueFund function inside poolOracle, there is a lack of inputs checks to avoid sending unnecessary transactions
## Impact
sending 0 value tokens to owner address may revert or will consume gas for nothing
## Code Snippet
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/oracle/PoolOracle.sol#L45-L51
## Tool used

Manual Review

## Recommendation
checks for input validity before sending any transaction

**Comment by quentin-abei** [comment]
[ ESCALATION ]
if owner want to rescue DAI token for example, 0 value transfer won't revert, the transaction will suceed and will trick him in thinking he successfully rescued the tokens ..

This is a medium
