### ISSUE TITLE
Vagner - `getTickAtSqrtRatio` and `mulDivFloor` function from `TickMath.sol` and `FullMath.sol` require overflow behavior and can render the contracts unusable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#31]
Vagner

high

# `getTickAtSqrtRatio` and `mulDivFloor` function from `TickMath.sol` and `FullMath.sol` require overflow behavior and can render the contracts unusable
## Summary
The function `getTickAtSqrtRatio` and `mulDivFloor` are used in multiple instances in the contract and those functions require overflow behavior, which will not happen, and can render multiple contracts unusable.
## Vulnerability Detail
`getTickAtSqrtRatio` from `TickMath.sol` is taked from UniswapV3 `TickMath` library, as can be seen here 
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/libraries/TickMath.sol#L69-L214
https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/libraries/TickMath.sol#L61-L204
and `mulDivFloor` was taken from UniswapV3 `FullMath` library 
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/libraries/FullMath.sol#L15-L110
https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/libraries/FullMath.sol#L14-L106
but libraries were made for compiler version less than 0.8.0, since it expects overflow behavior to work properly, but the instances where those functions were used in Kyber-Swap protocol are in contracts that are compiled with solidity version bigger than 0.8.0, which doesn't let overflow happen. `mulDivFloor`, for example, is used in most of the important functionalities in the contracts like `Pool.sol` 
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L279
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L452
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L640
## Impact
Impact is a high one since it can render the contracts like `Pool.sol`, `BasePositionManager.sol` , `AntiSnipAttackPositionManager.sol` unusable and loss of funds can occur in case of reverts of multiple fuctionalities.
## Code Snippet
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/libraries/TickMath.sol#L69-L214
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/libraries/FullMath.sol#L15-L110
## Tool used

Manual Review

## Recommendation
Use unchecked boxes in those two functions, since that is the way UniswapV3 solves this issues in their libraries.

**Comment by sherlock-admin2** [comment]
> Escalate
> It was specified by the judge the all of the calculation that requires overflow were put into `unchecked` boxes, but that is not true, the unchecked boxes were put only in some situations like here
> https://github.com/sherlock-audit/2023-07-kyber-swap/blob/e0cb622e7dacf4e8603507f3ea1c1073f9445dbe/ks-elastic-sc/contracts/periphery/libraries/LiquidityMath.sol#L24-L26  
> or here
> https://github.com/sherlock-audit/2023-07-kyber-swap/blob/e0cb622e7dacf4e8603507f3ea1c1073f9445dbe/ks-elastic-sc/contracts/periphery/libraries/LiquidityMath.sol#L41-L43
> but there are multiple instances where calculation that requires overflow behavior are not put in unchecked boxed like 
> https://github.com/sherlock-audit/2023-07-kyber-swap/blob/e0cb622e7dacf4e8603507f3ea1c1073f9445dbe/ks-elastic-sc/contracts/periphery/libraries/LiquidityMath.sol#L23
> or 
> https://github.com/sherlock-audit/2023-07-kyber-swap/blob/e0cb622e7dacf4e8603507f3ea1c1073f9445dbe/ks-elastic-sc/contracts/Pool.sol#L279
> https://github.com/sherlock-audit/2023-07-kyber-swap/blob/e0cb622e7dacf4e8603507f3ea1c1073f9445dbe/ks-elastic-sc/contracts/PoolTicksState.sol#L161
> I can put more examples, but I think these are enough and I believe that this should be treated as a High because revert on overflows can block important functionalities in most of the contracts and block the funds of the users, it is very important to use `unchecked` inside the function that I pointed out in the report since that is the intended way of using those functions.

    You've deleted an escalation for this issue.
