### ISSUE TITLE
tsvetanovv - The admin can set a swap fee of more than 20%

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#7]
tsvetanovv

high

# The admin can set a swap fee of more than 20%
## Summary

The admin can set a swap fee of more than 20% and this is forbidden according to the documentation.

> #### Is the admin/owner of the protocol/contracts TRUSTED or RESTRICTED?
> - Restricted - Owner shouldn’t be able to steal funds, but is trusted with setting fee recipient address and fee collection (up to 20%)
## Vulnerability Detail

In `Factory.sol` we have `enableSwapFee()` function:

```solidity
function enableSwapFee(uint24 swapFeeUnits, int24 tickDistance)
    public
    override
    onlyConfigMaster
  {
    require(swapFeeUnits < MathConstants.FEE_UNITS, 'invalid fee');
    // tick distance is capped at 16384 to prevent the situation where tickDistance is so large that
    // 16384 ticks represents a >5x price change with ticks of 1 bips
    require(tickDistance > 0 && tickDistance < 16384, 'invalid tickDistance');
    require(feeAmountTickDistance[swapFeeUnits] == 0, 'existing tickDistance');
    feeAmountTickDistance[swapFeeUnits] = tickDistance;
    emit SwapFeeEnabled(swapFeeUnits, tickDistance);
  }
```

This function allows `onlyConfigMaster` to set a swap fee and a tick distance. 
According to the readme, admin functions are RESTRICTED about theft of funds or the settlement of fees of more than 20%. 
In this case, the restriction we have is:
```solidity
require(swapFeeUnits < MathConstants.FEE_UNITS, 'invalid fee');
```
`MathConstants.FEE_UNITS` is `FEE_UNITS = 100000`. This means the fee can be up to 100% and the admin can set a value greater than 20% and harm the users.
## Impact

The admin can set a swap fee of more than 20% and hurt users which is forbidden according to the readme
## Code Snippet

https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Factory.sol#L151-L164

## Tool used

Manual Review

## Recommendation

To impose the 20% limit, the require statement should be changed to:
```solidity
require(swapFeeUnits <= 20000, 'invalid fee');
```

**Comment by cvetanovv** [comment]
Escalate 

This is a valid issue according to Sherlock rules.

- First, we see why the report is Excluded according to Lead Judge:
  `Don't see limit condition of 20% fee in contest docs`
I provide a link where this rule is found in the Readme:
**https://github.com/sherlock-audit/2023-07-kyber-swap-cvetanovv#q-is-the-adminowner-of-the-protocolcontracts-trusted-or-restricted**

- Second, in addition to the written report will also provide Sherlock's rules on why the report is valid:
1. Hierarchy of truth: Contest README > Sherlock rules for valid issues
2. In case of conflict between information in the README vs Sherlock rules, the README overrides Sherlock rules. 
3. If a protocol specifically mentions the restrictions imposed on the owner/admin issues describing an attack that results in bypassing these restrictions, they can be considered valid.

According to the README, admin functions are RESTRICTED about the settlement of more than 20% fees. This is explicitly clarified and goes into all Sherlock rules.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This is a valid issue according to Sherlock rules.
> 
> - First, we see why the report is Excluded according to Lead Judge:
>   `Don't see limit condition of 20% fee in contest docs`
> I provide a link where this rule is found in the Readme:
> **https://github.com/sherlock-audit/2023-07-kyber-swap-cvetanovv#q-is-the-adminowner-of-the-protocolcontracts-trusted-or-restricted**
> 
> - Second, in addition to the written report will also provide Sherlock's rules on why the report is valid:
> 1. Hierarchy of truth: Contest README > Sherlock rules for valid issues
> 2. In case of conflict between information in the README vs Sherlock rules, the README overrides Sherlock rules. 
> 3. If a protocol specifically mentions the restrictions imposed on the owner/admin issues describing an attack that results in bypassing these restrictions, they can be considered valid.
> 
> According to the README, admin functions are RESTRICTED about the settlement of more than 20% fees. This is explicitly clarified and goes into all Sherlock rules.
>   

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by securitygrid** [comment]
I think you may have misunderstood this sentence: but it is trusted with setting fee recipient address and fee collection (up to 20%). 
Admin should not maliciously set fees. More than 20% is considered malicious behavior.

**Comment by cvetanovv** [comment]
> I think you may have misunderstood this sentence: but it is trusted with setting fee recipient address and fee collection (up to 20%). Admin should not maliciously set fees. More than 20% is considered malicious behavior.

Well, that's exactly what I wrote. He can set more than 20% and this is malicious behavior.

**Comment by jingyi2811** [comment]
Escalate

This don’t agree with the escalation.

Per the contest readme.md, It does not specify the 20% limit for which i also agree with judge comment. A screenshot can be seen below,

<img width="580" alt="Screenshot 2023-09-22 at 10 58 50 AM" src="https://github.com/sherlock-audit/2023-07-kyber-swap-judging/assets/7101806/be35c796-3a0d-4d87-b465-faf029f6de4c">

Kyberswap contest page reference [here](https://audits.sherlock.xyz/contests/103)
A user is using the protocol will trust the protocol before using it and validate before swapping or doing transactions by seeing fee being charged. This fee is not enforced on user and I am sure user knowingly will think twice before proceeding with such fee being charged. In paractical scenario, We check twice before making transaction and fee being charged to us.
Since the admin seems to be trusted in this case as mentioned in report and therefore any trusted admin input paramter is not valid per the sherlock rules.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This don’t agree with the escalation.
> 
> Per the contest readme.md, It does not specify the 20% limit for which i also agree with judge comment. A screenshot can be seen below,
> 
> <img width="580" alt="Screenshot 2023-09-22 at 10 58 50 AM" src="https://github.com/sherlock-audit/2023-07-kyber-swap-judging/assets/7101806/be35c796-3a0d-4d87-b465-faf029f6de4c">
> 
> Kyberswap contest page reference [here](https://audits.sherlock.xyz/contests/103)
> A user is using the protocol will trust the protocol before using it and validate before swapping or doing transactions by seeing fee being charged. This fee is not enforced on user and I am sure user knowingly will think twice before proceeding with such fee being charged. In paractical scenario, We check twice before making transaction and fee being charged to us.
> Since the admin seems to be trusted in this case as mentioned in report and therefore any trusted admin input paramter is not valid per the sherlock rules.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
What you have attached is not from readme.md. I attach a screenshot to see what the README says. This is also in other people's repos. I don't know why the site UI shows otherwise, but the Contest README has the most weight. 
The report is certainly valid because a restriction is explicitly mentioned and can be bypassed. 
@jingyi2811 My report is written according to what is written in the README. And relative to the Sherlock rules it is crucial, regardless of whether people on the team say otherwise. 

![kyberswa](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/assets/25179264/83f78189-54c9-490a-a0e1-193713e42a40)

You can clearly see how it falls under all conditions and rules be valid. I described this in the first escalation. Since the repo is private, maybe one of Sherlock's team can confirm that I'm telling the truth.

**Comment by Trumpero** [comment]
Disagree with the escalation. The swap fee of a pool is fixed within each pool. There may be many pools with different swap fees for users to choose from. So there is no reason to limit the swap fee of a pool. The 20% limit on the fee in the initial state of the contest docs pertains to the government fee, which is used to collect a portion of the swap fee for the government (the remaining swap fee will be profit for liquidators). The Factory contract already includes a check to ensure that this government fee config will not exceed 20%: https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Factory.sol#L172
Therefore, this issue should be invalid.

**Comment by cvetanovv** [comment]
Since the admin is restricted he can set a swap fee of a pool 100% and steal the funds. This according to Sherlock documentation makes the report valid.

**Comment by Trumpero** [comment]
> Since the admin is restricted he can set a swap fee of a pool 100% and steal the funds. This according to Sherlock documentation makes the report valid.

@cvetanovv 
Please read my above comment carefully. The swap fee of a pool is fixed within each pool, so users can choose which one to use. It is only initialized when the pool is created and cannot be changed, so there is no reason to limit it. The `enableSwapFee` function mentioned in your report is used to adjust the `tickDistance` of the corresponding swapFeeUnits, not to change the swap fee of pools.

For example, there are multiple USDC-USDT pools with different swap fee configs in KyberSwap, and users can choose one of them to use. This config is attached with each pool and can't be changed.
<img width="485" alt="Screenshot 2023-10-02 at 20 25 46" src="https://github.com/sherlock-audit/2023-07-kyber-swap-judging/assets/114548871/ca26c1de-a644-4945-8760-156ce70d37a9">

**Comment by cvetanovv** [comment]
@Trumpero I looked at everything again and I think you're right

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue based on the above comments from the Lead Judge

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [jingyi2811](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/7/#issuecomment-1730734064): accepted
- [cvetanovv](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/7/#issuecomment-1727621186): rejected
